labels:
  0: 'noise'
  1: 'animal'
  2: 'human.pedestrian.adult'
  3: 'human.pedestrian.child'
  4: 'human.pedestrian.construction_worker'
  5: 'human.pedestrian.personal_mobility'
  6: 'human.pedestrian.police_officer'
  7: 'human.pedestrian.stroller'
  8: 'human.pedestrian.wheelchair'
  9: 'movable_object.barrier'
  10: 'movable_object.debris'
  11: 'movable_object.pushable_pullable'
  12: 'movable_object.trafficcone'
  13: 'static_object.bicycle_rack'
  14: 'vehicle.bicycle'
  15: 'vehicle.bus.bendy'
  16: 'vehicle.bus.rigid'
  17: 'vehicle.car'
  18: 'vehicle.construction'
  19: 'vehicle.emergency.ambulance'
  20: 'vehicle.emergency.police'
  21: 'vehicle.motorcycle'
  22: 'vehicle.trailer'
  23: 'vehicle.truck'
  24: 'flat.driveable_surface'
  25: 'flat.other'
  26: 'flat.sidewalk'
  27: 'flat.terrain'
  28: 'static.manmade'
  29: 'static.other'
  30: 'static.vegetation'
  31: 'vehicle.ego'
labels_16:
  0: 'noise'
  1: 'barrier'
  2: 'bicycle'
  3: 'bus'
  4: 'car'
  5: 'construction_vehicle'
  6: 'motorcycle'
  7: 'pedestrian'
  8: 'traffic_cone'
  9: 'trailer'
  10: 'truck'
  11: 'driveable_surface'
  12: 'other_flat'
  13: 'sidewalk'
  14: 'terrain'
  15: 'manmade'
  16: 'vegetation'
learning_map:
  1: 0
  5: 0
  7: 0
  8: 0
  10: 0
  11: 0
  13: 0
  19: 0
  20: 0
  0: 0
  29: 0
  31: 0
  9: 1
  14: 2
  15: 3
  16: 3
  17: 4
  18: 5
  21: 6
  2: 7
  3: 7
  4: 7
  6: 7
  12: 8
  22: 9
  23: 10
  24: 11
  25: 12
  26: 13
  27: 14
  28: 15
  30: 16

color_map: # rgb
  0: [0, 0, 0]  # Black.
  1: [70, 130, 180]  # Steelblue
  2: [0, 0, 230]  # Blue
  3: [135, 206, 235] # Skyblue,
  4: [100, 149, 237]  # Cornflowerblue
  5: [219, 112, 147]  # Palevioletred
  6: [0, 0, 128]  # Navy,
  7: [240, 128, 128]  # Lightcoral
  8: [138, 43, 226]  # Blueviolet
  9: [112, 128, 144]  # Slategrey
  10: [210, 105, 30]  # Chocolate
  11: [105, 105, 105]  # Dimgrey
  12: [47, 79, 79]  # Darkslategrey
  13: [188, 143, 143]  # Rosybrown
  14: [220, 20, 60]  # Crimson
  15: [255, 127, 80]  # Coral
  16: [255, 69, 0]  # Orangered
  17: [255, 158, 0]  # Orange
  18: [233, 150, 70]  # Darksalmon
  19: [255, 83, 0]
  20: [255, 215, 0]  # Gold
  21: [255, 61, 99]  # Red
  22: [255, 140, 0]  # Darkorange
  23: [255, 99, 71]  # Tomato
  24: [0, 207, 191]  # nuTonomy green
  25: [175, 0, 75]
  26: [75, 0, 75]
  27: [112, 180, 60]
  28: [222, 184, 135]  # Burlywood
  29: [255, 228, 196]  # Bisque
  30: [0, 175, 0]  # Green
  31: [255, 240, 245]
